Formación
ET12DE1Computacion/Fulbo12 pull request #15
Opened 2022-01-05 03:47 UTC by LucasMedina04

Agregado:
-Formación
*QuimicaJugadores
-Linea
*CantidadJugadores
*QuimicaJugadores
-PosicionEnCancha
*QuimicaJugador (declarado unicamente)

2022-01-05 21:17 UTC, luchoxx87 requested changes
Bien vamos por partes

## Clase PosicionEnCancha

- Para la parte de la química del jugador, recordá: si no hay jugador asignado (jugador es null) devuelve cero, caso contrario por ahora devolvé 10 (el calculo lo vamos a tener que discutir en grupo).
- Nombre de la propiedad: Yo lo dejaría en Futbolista, Jugador serian las personas que físicas que ordenan y disponen del equipo (así evitamos ambigüedades).
- Podríamos agregar una propiedad de solo lectura booleana que se llame `HayJugador` que devuelva `true` si es que efectivamente tiene un jugador asignado; `false` si es nulo.

## Linea

- Podemos simplificar el código de `CantidadJugadores` usando un método de extension Linq [Count](https://docs.microsoft.com/es-mx/dotnet/api/system.linq.enumerable.count?view=net-6.0#System_Linq_Enumerable_Count__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Boolean__), recordá agregar en el using el correspondiente `using System.Linq`. De todas formas el modo en que lo hiciste, funciona, es la forma casera.

2022-01-07 02:11 UTC, LucasMedina04 commented
Ya modifique lo que me dijo y unas cositas más, no si es que hay alguna forma de "Actualizar" un Pull Request así que se lo comento por aca.

2022-04-02 00:27 UTC, luchoxx87 requested changes
Muy bien @LucasMedina04, ahí me di cuenta que para poder armar la cadena de la formación, una cosa es la cantidad de jugadores por linea que hay en realidad (por ahora no la usamos, pero lo haremos, así que dejalo ahí) y la otra es la cantidad de posiciones en total por linea (esta si la vamos a usar para la cadena).

Te hice también unas sugerencias también con respecto a la implementación de algunas propiedades usando el feature de la expresión lambda.

Agrega estos cambios porfas y volve a presentar, ahí te doy una mano con el tema de la construcción de la cadena de la formación.

¡Exitos!

2022-04-02 00:27 UTC, luchoxx87 commented on src/Fulbo12.Core/Formacion/Linea.cs
> +        public byte QuimicaJugadores
Podrías usar el feature del lenguaje y te quedaría algo como
```csharp
public byte QuimicaJugadores
    => Convert.ToByte(Posiciones.Sum(p => p.QuimicaJugador));
```

2022-04-02 03:02 UTC, LucasMedina04 commented
Ya agregué una propiedad `Linea.CantidadPosiciones` a usar en `Formacion`.
Simplifique `Linea.QuimicaJugadores`, `Linea.CantidadJugadores` y `Formacion.QuimicaJugadores`.

2022-04-03 15:46 UTC, luchoxx87 reviewed
Muy bien @LucasMedina04, ahora vamos a bancar unos días a que alguno de los muchachos de 6to7ma haga algunos test sobre el código de este PR (justo les estoy dando eso a la tarde)y cuando corran, fusiono este PR al del repo ✌

2022-04-03 15:46 UTC, luchoxx87 commented on src/Fulbo12.Core/Formacion/Formacion.cs
> +            //TODO usar la prop PosicionesPorLinea y el método string join
Para este TODO mira la [documentación de String.Join](https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=net-6.0#system-string-join-1(system-string-system-collections-generic-ienumerable((-0)))) en MSDN @LucasMedina04.

2022-04-07 23:07 UTC, LucasMedina04 commented
@luchoxx87 Tengo que preguntar.
¿El código que modificó no dará errores?
Me refiero a que se verificara si ```NumeroCamiseta``` que puede ser ```null``` es igual a ```numeroCamiseta``` que no puede ser ```null```.
¿O el código se detendrá al verificar que ```NumeroCamiseta``` es ```null```?

2022-04-07 23:19 UTC, luchoxx87 commented
> @luchoxx87 Tengo que preguntar. ¿El código que modificó no dará errores? Me refiero a que se verificara si `NumeroCamiseta` que puede ser `null` es igual a `numeroCamiseta` que no puede ser `null`. ¿O el código se detendrá al verificar que `NumeroCamiseta` es `null`?

Buenas @LucasMedina04, en la expresión
```csharp
public bool EsNumero(byte numeroCamiseta)
    => NumeroCamiseta.HasValue && NumeroCamiseta == numeroCamiseta;
```
la propiedad `HasValue`, evaluá si la variable posee o no un valor (es decir, devuelve bool) y como se evalúa primero de izquierda a derecha, veamos 3 escenarios:
1. No tiene numero de camiseta: en este caso, `NumeroCamiseta.HasValue` devuelve `false` y como esta en una conjunción, el compilador ni se molesta en verificar la segunda condición y devuelve falso.
1. Camiseta con valor x y pregunto si es y: `NumeroCamiseta.HasValue` devuelve `true` (porque si tiene un valor) y como la segunda condición da `false` (x es distinto de y), toda la expresión devuelve `false`.
1. Camiseta con valor x y pregunto si es x: `NumeroCamiseta.HasValue` devuelve `true` (porque si tiene un valor) y como la segunda condición da `true` (x es igual a x), toda la expresión devuelve `true`.

El _truco_ esta en saber el orden de evaluación (si las condiciones estuviera al revés, ahí si se podría romper).

2022-04-07 23:22 UTC, LucasMedina04 commented
Dudas despejadas, esto me servirá en el futuro.
Gracias!!

2022-04-10 22:29 UTC, luchoxx87 requested changes

2022-04-10 22:29 UTC, luchoxx87 commented on src/Fulbo12.Core/Formacion/Formacion.cs
> +                    i++;
Ojo acá @MMorandiniGit , tené en cuenta que es el mismo `for` el que va a ir incrementando el valor de `i` (esta linea no va).

2022-04-19 05:49 UTC, merged

2023-06-21 18:14 UTC, luchoxx87 commented
Buenas, hoy en clase hablamos de agregar unas clases para ayudar a la persistencia de:

- [ ] La `Alineacion` (Formación esta agregada por ellas)
- [ ] Y la `PosicionFormacion` (Formación va a estar compuesta de estas clases).